# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          output_action: gist
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: IvanHanloth
          template: classic
          base: header, activity, community, repositories, metadata
          
      - name: Commit
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.commit.svg
          output_action: gist
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: IvanHanloth
          template: classic
          base: ""
          config_timezone: Etc/GMT-8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Mostused
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.mostused.svg
          output_action: gist
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          token: ${{ secrets.METRICS_TOKEN }}

          user: IvanHanloth
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
