# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.1.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: IvanHanloth
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Etc/GMT-8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.2.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: IvanHanloth
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Etc/GMT-8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
